/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/new-room.glb -K -k 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Office3(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/new-room.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model001"
          position={[-0.431, -0.394, -0.15]}
          rotation={[-1.558, 0.013, 3.087]}
          scale={0.005}
        >
          <group
            name="2da2326d0b3e4a7d9b49861455ee94a0fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode001">
              <group
                name="Base"
                position={[2.684, -0.125, 67.889]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={100}
              >
                <mesh
                  name="Base_Base_0"
                  geometry={nodes.Base_Base_0.geometry}
                  material={materials.Base}
                />
              </group>
              <group
                name="Display"
                position={[2.684, 83.159, 64.775]}
                rotation={[-1.484, 0, -Math.PI]}
                scale={100}
              >
                <mesh
                  name="Display_iMac_0"
                  geometry={nodes.Display_iMac_0.geometry}
                  material={materials.iMac}
                />
              </group>
              <group
                name="Keyboard"
                position={[22.163, 1.566, -0.477]}
                rotation={[-1.58, 0, 3.139]}
                scale={100}
              >
                <mesh
                  name="Keyboard_Keyboard_0"
                  geometry={nodes.Keyboard_Keyboard_0.geometry}
                  material={materials["Keyboard.001"]}
                />
              </group>
              <group
                name="Mouse001"
                position={[-49.729, 1.055, 2.455]}
                rotation={[-Math.PI / 2, 0, 0.023]}
                scale={100}
              >
                <mesh
                  name="Mouse001_Mouse_0"
                  geometry={nodes.Mouse001_Mouse_0.geometry}
                  material={materials.Mouse}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.329}
        >
          <group
            name="Small_Officefbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group
                name="Backdrop"
                position={[529.896, 120.434, 0]}
                rotation={[0, -1.571, 0]}
                scale={50}
              >
                <mesh
                  name="Backdrop_Backdrop_0"
                  geometry={nodes.Backdrop_Backdrop_0.geometry}
                  material={materials.Backdrop}
                />
              </group>
              <group
                name="Small_Office"
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={380}
              >
                <mesh
                  name="Small_Office_Bin_0"
                  geometry={nodes.Small_Office_Bin_0.geometry}
                  material={materials.material_22}
                />
                <mesh
                  name="Small_Office_BlackTrim_0"
                  geometry={nodes.Small_Office_BlackTrim_0.geometry}
                  material={materials.BlackTrim}
                />
                <mesh
                  name="Small_Office_Chair_0"
                  geometry={nodes.Small_Office_Chair_0.geometry}
                  material={materials.Chair}
                  position={[-0.281, -0.397, 0]}
                  rotation={[0, 0, 0.595]}
                />
                <mesh
                  name="Small_Office_Chrome_0"
                  geometry={nodes.Small_Office_Chrome_0.geometry}
                  material={materials.Chrome}
                  position={[-0.007, 0.004, 0.219]}
                  scale={[1.002, 1, 1.234]}
                />
                <mesh
                  name="Small_Office_Clockface_0"
                  geometry={nodes.Small_Office_Clockface_0.geometry}
                  material={materials.Clockface}
                />
                <mesh
                  name="Small_Office_ClockOutside_0"
                  geometry={nodes.Small_Office_ClockOutside_0.geometry}
                  material={materials.ClockOutside}
                />
                <mesh
                  name="Small_Office_ClockWindow_0"
                  geometry={nodes.Small_Office_ClockWindow_0.geometry}
                  material={materials.ClockWindow}
                />
                <mesh
                  name="Small_Office_Cupboard_0"
                  geometry={nodes.Small_Office_Cupboard_0.geometry}
                  material={materials.Cupboard}
                />
                <mesh
                  name="Small_Office_Curtain_0"
                  geometry={nodes.Small_Office_Curtain_0.geometry}
                  material={materials.Curtain}
                />
                <mesh
                  name="Small_Office_DeskPainting_0"
                  geometry={nodes.Small_Office_DeskPainting_0.geometry}
                  material={materials.DeskPainting}
                />
                <mesh
                  name="Small_Office_DeskPaintingFrame_0"
                  geometry={nodes.Small_Office_DeskPaintingFrame_0.geometry}
                  material={materials.DeskPaintingFrame}
                />
                <mesh
                  name="Small_Office_Dirt_0"
                  geometry={nodes.Small_Office_Dirt_0.geometry}
                  material={materials.Dirt}
                />
                <mesh
                  name="Small_Office_Floor_0"
                  geometry={nodes.Small_Office_Floor_0.geometry}
                  material={materials.Floor}
                />
                <mesh
                  name="Small_Office_Keyboard_0"
                  geometry={nodes.Small_Office_Keyboard_0.geometry}
                  material={materials.Keyboard}
                />
                <mesh
                  name="Small_Office_Leaves_0"
                  geometry={nodes.Small_Office_Leaves_0.geometry}
                  material={materials.Leaves}
                />
                <mesh
                  name="Small_Office_LightEmissive_0"
                  geometry={nodes.Small_Office_LightEmissive_0.geometry}
                  material={materials.LightEmissive}
                />
                <mesh
                  name="Small_Office_LightSurround_0"
                  geometry={nodes.Small_Office_LightSurround_0.geometry}
                  material={materials.LightSurround}
                />
                <mesh
                  name="Small_Office_Notepad_0"
                  geometry={nodes.Small_Office_Notepad_0.geometry}
                  material={materials.Notepad}
                />
                <mesh
                  name="Small_Office_NotepadBook_0"
                  geometry={nodes.Small_Office_NotepadBook_0.geometry}
                  material={materials.NotepadBook}
                />
                <mesh
                  name="Small_Office_Painting2_0"
                  geometry={nodes.Small_Office_Painting2_0.geometry}
                  material={materials.Painting2}
                />
                <mesh
                  name="Small_Office_Painting3_0"
                  geometry={nodes.Small_Office_Painting3_0.geometry}
                  material={materials.Painting3}
                />
                <mesh
                  name="Small_Office_Painting_0"
                  geometry={nodes.Small_Office_Painting_0.geometry}
                  material={materials.Painting}
                />
                <mesh
                  name="Small_Office_Plug_0"
                  geometry={nodes.Small_Office_Plug_0.geometry}
                  material={materials.Plug}
                />
                <mesh
                  name="Small_Office_Pot_0"
                  geometry={nodes.Small_Office_Pot_0.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Small_Office_Screen_0"
                  geometry={nodes.Small_Office_Screen_0.geometry}
                  material={materials.Screen}
                />
                <mesh
                  name="Small_Office_SkirtingBoard_0"
                  geometry={nodes.Small_Office_SkirtingBoard_0.geometry}
                  material={materials.SkirtingBoard}
                />
                <mesh
                  name="Small_Office_Table_0"
                  geometry={nodes.Small_Office_Table_0.geometry}
                  material={materials.Table}
                />
                <mesh
                  name="Small_Office_Towel_0"
                  geometry={nodes.Small_Office_Towel_0.geometry}
                  material={materials.Towel}
                />
                <mesh
                  name="Small_Office_Wall_0"
                  geometry={nodes.Small_Office_Wall_0.geometry}
                  material={materials.Wall}
                />
                <mesh
                  name="Small_Office_WallPictureFrames_0"
                  geometry={nodes.Small_Office_WallPictureFrames_0.geometry}
                  material={materials.WallPictureFrames}
                />
                <mesh
                  name="Small_Office_Window_0"
                  geometry={nodes.Small_Office_Window_0.geometry}
                  material={materials.Window}
                />
                <mesh
                  name="Small_Office_WindowFrame_0"
                  geometry={nodes.Small_Office_WindowFrame_0.geometry}
                  material={materials.WindowFrame}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="typing"
          position={[-0.474, -1.215, 0.409]}
          rotation={[Math.PI, -0.084, Math.PI]}
          scale={[1, 1.199, 1]}
        >
          <group name="Armature001">
            <primitive object={nodes.Hips} />
            <skinnedMesh
              name="Wolf3D_Hair001"
              geometry={nodes.Wolf3D_Hair001.geometry}
              material={materials["Wolf3D_Hair.003"]}
              skeleton={nodes.Wolf3D_Hair001.skeleton}
            />
            <skinnedMesh
              name="EyeLeft001"
              geometry={nodes.EyeLeft001.geometry}
              material={materials["Wolf3D_Eye.003"]}
              skeleton={nodes.EyeLeft001.skeleton}
            />
            <skinnedMesh
              name="EyeRight001"
              geometry={nodes.EyeRight001.geometry}
              material={materials["Wolf3D_Eye.003"]}
              skeleton={nodes.EyeRight001.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Body001"
              geometry={nodes.Wolf3D_Body001.geometry}
              material={materials["Wolf3D_Body.003"]}
              skeleton={nodes.Wolf3D_Body001.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Head001"
              geometry={nodes.Wolf3D_Head001.geometry}
              material={materials["Wolf3D_Skin.003"]}
              skeleton={nodes.Wolf3D_Head001.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Outfit_Bottom001"
              geometry={nodes.Wolf3D_Outfit_Bottom001.geometry}
              material={materials["Wolf3D_Outfit_Bottom.003"]}
              skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Outfit_Footwear001"
              geometry={nodes.Wolf3D_Outfit_Footwear001.geometry}
              material={materials["Wolf3D_Outfit_Footwear.003"]}
              skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Outfit_Top001"
              geometry={nodes.Wolf3D_Outfit_Top001.geometry}
              material={materials["Wolf3D_Outfit_Top.003"]}
              skeleton={nodes.Wolf3D_Outfit_Top001.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Teeth001"
              geometry={nodes.Wolf3D_Teeth001.geometry}
              material={materials["Wolf3D_Teeth.003"]}
              skeleton={nodes.Wolf3D_Teeth001.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/new-room.glb");
