/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/new-room2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Office(props) {
  const { nodes, materials } = useGLTF("models/new-room2.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.431, -0.394, -0.15]}
        rotation={[-1.558, 0.013, 3.087]}
        scale={0.005}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Base_Base_0.geometry}
            material={materials.Base}
            position={[2.684, -0.125, 67.889]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            geometry={nodes.Display_iMac_0.geometry}
            material={materials.iMac}
            position={[2.684, 83.159, 64.775]}
            rotation={[-1.484, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            geometry={nodes.Keyboard_Keyboard_0.geometry}
            material={materials["Keyboard.001"]}
            position={[22.163, 1.566, -0.477]}
            rotation={[-1.58, 0, 3.139]}
            scale={100}
          />
          <mesh
            geometry={nodes.Mouse001_Mouse_0.geometry}
            material={materials.Mouse}
            position={[-49.729, 1.055, 2.455]}
            rotation={[-Math.PI / 2, 0, 0.023]}
            scale={100}
          />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.329}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={380}>
            <mesh
              geometry={nodes.Small_Office_Bin_0.geometry}
              material={materials.material_22}
            />
            <mesh
              geometry={nodes.Small_Office_BlackTrim_0.geometry}
              material={materials.BlackTrim}
            />
            <mesh
              geometry={nodes.Small_Office_Chair_0.geometry}
              material={materials.Chair}
              position={[-0.281, -0.397, 0]}
              rotation={[0, 0, 0.595]}
            />
            <mesh
              geometry={nodes.Small_Office_Chrome_0.geometry}
              material={materials.Chrome}
              position={[-0.007, 0.004, 0.219]}
              scale={[1.002, 1, 1.234]}
            />
            <mesh
              geometry={nodes.Small_Office_Clockface_0.geometry}
              material={materials.Clockface}
            />
            <mesh
              geometry={nodes.Small_Office_ClockOutside_0.geometry}
              material={materials.ClockOutside}
            />
            <mesh
              geometry={nodes.Small_Office_ClockWindow_0.geometry}
              material={materials.ClockWindow}
            />
            <mesh
              geometry={nodes.Small_Office_Cupboard_0.geometry}
              material={materials.Cupboard}
            />
            <mesh
              geometry={nodes.Small_Office_Curtain_0.geometry}
              material={materials.Curtain}
            />
            <mesh
              geometry={nodes.Small_Office_DeskPainting_0.geometry}
              material={materials.DeskPainting}
            />
            <mesh
              geometry={nodes.Small_Office_DeskPaintingFrame_0.geometry}
              material={materials.DeskPaintingFrame}
            />
            <mesh
              geometry={nodes.Small_Office_Dirt_0.geometry}
              material={materials.Dirt}
            />
            <mesh
              geometry={nodes.Small_Office_Floor_0.geometry}
              material={materials.Floor}
            />
            <mesh
              geometry={nodes.Small_Office_Keyboard_0.geometry}
              material={materials.Keyboard}
            />
            <mesh
              geometry={nodes.Small_Office_Leaves_0.geometry}
              material={materials.Leaves}
            />
            <mesh
              geometry={nodes.Small_Office_LightEmissive_0.geometry}
              material={materials.LightEmissive}
            />
            <mesh
              geometry={nodes.Small_Office_LightSurround_0.geometry}
              material={materials.LightSurround}
            />
            <mesh
              geometry={nodes.Small_Office_Notepad_0.geometry}
              material={materials.Notepad}
            />
            <mesh
              geometry={nodes.Small_Office_NotepadBook_0.geometry}
              material={materials.NotepadBook}
            />
            <mesh
              geometry={nodes.Small_Office_Painting2_0.geometry}
              material={materials.Painting2}
            />
            <mesh
              geometry={nodes.Small_Office_Painting3_0.geometry}
              material={materials.Painting3}
            />
            <mesh
              geometry={nodes.Small_Office_Painting_0.geometry}
              material={materials.Painting}
            />
            <mesh
              geometry={nodes.Small_Office_Plug_0.geometry}
              material={materials.Plug}
            />
            <mesh
              geometry={nodes.Small_Office_Pot_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Small_Office_Screen_0.geometry}
              material={materials.Screen}
            />
            <mesh
              geometry={nodes.Small_Office_SkirtingBoard_0.geometry}
              material={materials.SkirtingBoard}
            />
            <mesh
              geometry={nodes.Small_Office_Table_0.geometry}
              material={materials.Table}
            />
            <mesh
              geometry={nodes.Small_Office_Towel_0.geometry}
              material={materials.Towel}
            />
            <mesh
              geometry={nodes.Small_Office_Wall_0.geometry}
              material={materials.Wall}
            />
            <mesh
              geometry={nodes.Small_Office_WallPictureFrames_0.geometry}
              material={materials.WallPictureFrames}
            />
            <mesh
              geometry={nodes.Small_Office_Window_0.geometry}
              material={materials.Window}
            />
            <mesh
              geometry={nodes.Small_Office_WindowFrame_0.geometry}
              material={materials.WindowFrame}
            />
          </group>
          <mesh
            geometry={nodes.Backdrop_Backdrop_0.geometry}
            material={materials.Backdrop}
            position={[529.896, 120.434, 0]}
            rotation={[0, -1.571, 0]}
            scale={50}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/new-room2.glb");
